# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-24 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ih', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='hours',
        ),
        migrations.AddField(
            model_name='task',
            name='frequency',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='per_time',
            field=models.IntegerField(default=1),
        ),
    ]
