# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-13 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ih', '0004_auto_20180512_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='icon',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='icon',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
