# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-16 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ih', '0005_auto_20180512_2103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskCompletion',
            new_name='Goal',
        ),
    ]
