# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-16 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ih', '0006_auto_20180516_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='started',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='targeted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='goal',
            name='completed',
            field=models.DateTimeField(null=True),
        ),
    ]
